### ISSUE TITLE
Missing configuration example

### ISSUE THREAD

**Issue by plippe** [sirocchj/sbt-api-builder#1]
Hi,

The config was a bit hard to setup. I tried to copy a few examples from [the cli documentation](https://github.com/apicollective/apibuilder-cli#update), but nothing really worked.

Adding an example configuration would make the process easier, or even generating one if the config file is missing, similarly to how the config folder is generated. 

```
code:
  apicollective:
    apibuilder:
      version: latest
      generators:
        - generator: http4s_0_18
          files:
            - '*ModelsJson.scala'
            - '*Server.scala'
```
